"""Initial 2

Revision ID: 1826ee4b904e
Revises: 629abebf5e3e
Create Date: 2025-05-15 10:54:55.803961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1826ee4b904e'
down_revision: Union[str, None] = '629abebf5e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('can_edit_content', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('USER_CREATE', 'ADMIN_CREATE', 'UPDATE', 'DELETE', 'CHANGE_STATUS', 'LOGIN', 'LOGOUT', name='actionenum'), nullable=False),
    sa.Column('entity', sa.Enum('ORDER', 'REQUEST', 'CLIENT', 'ADMIN', 'SERVICE', 'SERVICE_CATEGORY', 'PROJECT', 'PROJECT_CATEGORY', 'CONTACT', name='entityenum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('request', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('request', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('request', 'updated_at')
    op.drop_column('order', 'updated_at')
    op.drop_table('admin_token')
    op.drop_table('action_history')
    op.drop_table('admin')
    # ### end Alembic commands ###
