"""Changes

Revision ID: 67753a0bb332
Revises: d8a51fde0350
Create Date: 2025-06-05 23:59:32.471477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67753a0bb332'
down_revision: Union[str, None] = 'd8a51fde0350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advantage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advantage', sa.String(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('project', 'category_id')
    op.drop_constraint('service_category_id_fkey', 'service', type_='foreignkey')
    op.drop_column('service', 'category_id')
    op.drop_table('project_category')
    op.drop_table('service_category')
    op.add_column('project', sa.Column('datetime', sa.Date(), nullable=False))
    op.add_column('project', sa.Column('address', sa.String(), nullable=False))
    op.add_column('project', sa.Column('area', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('period', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'service', ['service_id'], ['id'])
    op.drop_column('project', 'image')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('service_category_id_fkey', 'service', 'service_category', ['category_id'], ['id'])
    op.add_column('project', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key('project_category_id_fkey', 'project', 'project_category', ['category_id'], ['id'])
    op.drop_column('project', 'service_id')
    op.drop_column('project', 'price')
    op.drop_column('project', 'period')
    op.drop_column('project', 'area')
    op.drop_column('project', 'address')
    op.drop_column('project', 'datetime')
    op.create_table('service_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='service_category_pkey')
    )
    op.create_table('project_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='project_category_pkey')
    )
    op.drop_table('project_media')
    op.drop_table('feature')
    op.drop_table('stage')
    op.drop_table('advantage')
    # ### end Alembic commands ###
