"""ClientToken code

Revision ID: e32415c139c4
Revises: 28c928b09b9b
Create Date: 2025-05-21 04:05:07.024458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32415c139c4'
down_revision: Union[str, None] = '28c928b09b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_token', sa.Column('code', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_token', 'code')
    # ### end Alembic commands ###
